version: 2

project_name: homeyctl

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X github.com/fishfisher/homeyctl/cmd.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['binary']
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

brews:
  - name: homeyctl
    repository:
      owner: fishfisher
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/fishfisher/homeyctl
    description: "CLI for controlling Homey smart home"
    download_strategy: FishfisherPrivateReleaseDownloadStrategy
    custom_require: lib/private_strategy
    install: |
      bin.install Dir["homeyctl*"].first => "homeyctl"
    test: |
      assert_match "homeyctl", shell_output("#{bin}/homeyctl version")

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
